apiVersion: v1
kind: Service
metadata:
  name: {{ include "djangob.fullname" . }}
  labels:
    {{- include "djangob.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      NodePort: 30080
  selector:
    {{- include "djangob.selectorLabels" . | nindent 4 }}
